package tpl.ci.gradle

import tpl.ci.gradle.tpl_GradleCiPipeline

@Library('tikal-pipelib') _

node("linux-host-slave") {
    pipeline = new tpl_GradleCiPipeline(this)
    pipeline.run()

    def buildResult = pipeline.getCurrentBuildResult() != null ? pipeline.getCurrentBuildResult() : 'SUCCESS'
    def buildNum = env.BUILD_NUMBER
    def buildURL = env.BUILD_URL

    emailext body: 'Your Jenkins Job, Num. ' + buildNum + ' Finished With Status => ' +
             buildResult + '\nYou Can Reach The Test Result Page Here. ' +
            buildURL + 'cucumber-html-reports/overview-features.html',
             subject: 'Build ' + env.BUILD_NUMBER + ' Result',
            to: 'itai@tikalk.com'
     }

